server:
  port: 80    # What port should the gateway we listening on
  ssl: false   # Should we use SSL?  If you do, change the port to 443
  title: Massyn Nginx Web Gateway
sites:
  mrtg:
    title: MRTG
    description: The Multi-Router Traffic Graphing tool
    location: /var/www/html/mrtg/
reverse:
  router:
    title: Router
    description: Our router
    location: http://192.168.0.1
  ollama:
    title: ollama
    location: http://192.168.0.5:8080
# groups:
#   - phil
# users:
#   phil: password123
# groups:
#   admin:
#     - phil
